from typing import Any

from fastmcp import FastMCP

import client

mcp = FastMCP(
    name="dbt-mcp",
    instructions=(
        "Access to a dbt project: inspect model errors, run models, read test results, "
        "trace lineage, and browse the project manifest. "
        "All read operations parse files already on disk (target/run_results.json, "
        "target/manifest.json) — they reflect the last dbt invocation, not live warehouse state. "
        "Use run_model to trigger a fresh execution when up-to-date results are needed."
    ),
)


@mcp.tool()
def get_model_error(model_name: str) -> dict[str, Any]:
    """
    Return the outcome of the last run for a specific dbt model.

    Reads target/run_results.json — reflects the most recent dbt run, not the current
    warehouse state. If the project has not been run yet, returns {success: false}.

    Result shape depends on outcome:
    - Model ran successfully: {success: true, model, status: "pass"}
    - Model failed: {success: true, model, status: "error"|"skip"|...,
                     message, compiled_sql, timing}
    - File missing: {success: false, error: "run_results.json not found"}
    - Model not in results: {success: false, error: "Model '...' not found ..."}

    compiled_sql contains the fully rendered SQL dbt attempted to execute — useful for
    diagnosing syntax or logic errors. timing is a list of phase durations (compile, execute).

    Use this tool to investigate why a specific model failed after a dbt run.
    Prefer get_test_results for test failures; use get_model_lineage to trace upstream causes.

    Args:
        model_name: The short model name (e.g. "orders"), not the full node ID.
    """
    return client.get_model_error(model_name)


@mcp.tool()
def run_model(model_name: str) -> dict[str, Any]:
    """
    Execute a single dbt model against the configured warehouse target.

    Runs `dbt run --select <model_name>` programmatically using dbtRunner.
    Uses DBT_PROJECT_DIR, DBT_PROFILES_DIR, and DBT_TARGET from the environment.

    Returns:
    - success: true means the MCP call completed without an unhandled exception.
      It does NOT mean the model built successfully — check status for that.
    - status: dbt execution outcome — "success", "error", "skip", or "no_results"
      (no_results means dbt ran but matched no nodes, usually a wrong model name).
    - rows_affected: number of rows written, or null if the adapter did not report it
      (common for view materializations and some warehouses).
    - execution_time: wall-clock seconds for the node, or null if unavailable.
    - message: only present when status is "error" — contains the adapter error text.

    Call get_model_error after a failed run to retrieve compiled_sql and full timing.
    Call get_test_results after a successful run to verify data quality assertions.

    Args:
        model_name: The short model name (e.g. "orders"), not the full node ID.
    """
    return client.run_model(model_name)


@mcp.tool()
def get_test_results(model_name: str | None = None) -> dict[str, Any]:
    """
    Return test results from the last dbt test run.

    Reads target/run_results.json and enriches each result with metadata from
    target/manifest.json (test type, column name, owning model).

    When model_name is provided, returns only tests that directly reference that model
    (resolved via manifest dependency graph — more accurate than name matching).
    When model_name is None, returns all test results from the last run.

    Each test entry contains:
    - name: test node name (e.g. "not_null_orders_order_id")
    - model: the model under test, or null if the manifest was unavailable
    - status: "pass", "fail", "error", or "warn"
    - message: failure message or row count for failing tests; empty string on pass
    - test_type: "not_null", "unique", "accepted_values", "relationships", or null
      for custom generic/singular tests
    - column: column under test, or null for model-level or singular tests

    Returns {success: false, error: "run_results.json not found"} if the project
    has not been run. Returns an empty tests list if no tests were executed in the
    last run (e.g. only `dbt run` was called, not `dbt test`).

    Use get_model_error to investigate model compilation/execution failures;
    this tool is specifically for data quality test outcomes.

    Args:
        model_name: Short model name to filter by, or None for all tests.
    """
    return client.get_test_results(model_name)


@mcp.tool()
def get_model_lineage(model_name: str) -> dict[str, Any]:
    """
    Return the direct upstream and downstream dependencies of a dbt model.

    Reads target/manifest.json, which is generated by `dbt compile` or `dbt run`.
    Reflects the project graph at compile time — does not require a successful run.

    Returns:
    - upstream: list of node names (models, seeds, sources) this model directly
      depends on via ref() or source() calls. One level only — not transitive.
    - downstream: list of model names that directly depend on this model.
      Includes models, snapshots, and exposures if they appear in child_map.
    - node_id: full dbt unique ID (e.g. "model.my_project.orders") for cross-referencing.

    upstream and downstream contain short names (last segment of the node ID), not
    full unique IDs. Use get_manifest to map names back to paths or tags if needed.

    Returns {success: false, error: "Model '...' not found in manifest"} if the model
    does not exist in the compiled graph (check spelling or run `dbt compile` first).

    Use this tool to understand impact before modifying a model, or to trace the
    root cause of a failure through the dependency chain.

    Args:
        model_name: The short model name (e.g. "orders"), not the full node ID.
    """
    return client.get_model_lineage(model_name)


@mcp.tool()
def get_manifest() -> dict[str, Any]:
    """
    Return a compressed summary of the dbt project manifest.

    Reads target/manifest.json. Useful for getting a project overview without
    loading the full manifest (which can be many megabytes on large projects).

    Returns:
    - project_name: dbt project name from dbt_project.yml
    - dbt_version: dbt-core version used to compile the manifest
    - generated_at: ISO-8601 timestamp of the last `dbt compile` or `dbt run`
    - model_count / source_count / test_count: counts by resource type
    - models: list of {name, node_id, path, tags} for every model node
      - path: relative path within the models/ directory
      - tags: list of strings; empty list if no tags are defined

    Does not include sources, snapshots, exposures, or test node details.
    Use get_model_lineage to explore a specific model's graph position.
    Use get_test_results to see test outcomes.

    Returns {success: false, error: "manifest.json not found"} if the project
    has never been compiled (run `dbt compile` or `dbt run` first).
    """
    return client.get_manifest()


if __name__ == "__main__":
    mcp.run()
